---
- hosts: all
  become: yes
  become_method: sudo
  vars_files:
    - vars/all.yml
  roles:
#    - server
#    - vagrant_local
#    - nginx
#    - mysql
#    - php
#    - composer
#    - xdebug
#    - redis
    - app
